name: frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('frontend/package-lock.json') }}
      - name: Build
        run: |
          npm ci
          npm run build
        working-directory: frontend
      - name: test
        run: npm run test
        working-directory: frontend
      - name: run chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: frontend
