name: frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('frontend/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
        working-directory: frontend
      - name: eslint review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          workdir: frontend
      - name: Build
        run: npm run build
        working-directory: frontend
      - name: test
        run: npm run test
        working-directory: frontend
      - name: run chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: frontend
          onlyChanged: true
